#include "kh2coop/NativeRecordContent.hpp"
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
using namespace kh2coop;
namespace {
int errors = 0, checks = 0;
void check(bool good, const char* name) {
    ++checks; if (!good) ++errors;
    std::cout << (good ? "PASS: " : "FAIL: ") << name << '\n';
}
std::vector<std::uint8_t> hex(std::string_view text) {
    if (text.size() % 2) throw std::runtime_error("odd fixture hex");
    auto nibble=[](char c)->unsigned { if(c>='0'&&c<='9')return unsigned(c-'0');
        if(c>='a'&&c<='f')return unsigned(c-'a'+10);
        if(c>='A'&&c<='F')return unsigned(c-'A'+10);
        throw std::runtime_error("bad fixture hex"); };
    std::vector<std::uint8_t> result;
    for(std::size_t i=0;i<text.size();i+=2)result.push_back(static_cast<std::uint8_t>(16*nibble(text[i])+nibble(text[i+1])));
    return result;
}
template<std::size_t N> std::array<std::uint8_t,N> fixed(std::string_view text) {
    const auto bytes=hex(text); if(bytes.size()!=N)throw std::runtime_error("wrong fixture size");
    std::array<std::uint8_t,N> result{}; std::copy(bytes.begin(),bytes.end(),result.begin());return result;
}
struct GoldenRecord { const char* raw; const char* encoding; const char* digest; };
struct GoldenDefinition { std::uint32_t group; const char* header; const char* encoding;
    const char* digest; const char* projectionDigest; std::vector<GoldenRecord> records; };
// Frozen 20261004 catalog: 10 definitions / 26 full records. Expected encodings
// are the independently reviewed design JSON, not generated by this C++ code.
const std::vector<GoldenDefinition> goldens{
    {808476525u, "0100010003000000000000000000000000000000000000000000000006000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f30300101000300fbf27e22e4618d4cd87236daf9e6069b08516a2377d1e5f53ea47c762455acd9",
     "05BB781C5ED6DD4AD28EB6BD1C81668DC0DB9BDEDA3AFC9F3A950C0594F16D0D", "8B6765F124AF4E7286E4E12202F72D800A603280C410BB79C03808D906D8B81A", {
        {"36020000b4ab92b6fdff81c300c0f344000000000000000000000000010003000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310005bb781c5ed6dd4ad28eb6bd1c81668dc0db9bdeda3afc9f3a950c0594f16d0d000003004685e5e96861876186a4628efbb3b88cf2394e3f6e0c5b560c4f07cafb578367", "2532594B2FF9E33E304D2AD0DE1F21FA1D382CB794C78796550362D849BFDF97"},
        {"3702000000001643000082c30040e744000000000000000000000000010004000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310005bb781c5ed6dd4ad28eb6bd1c81668dc0db9bdeda3afc9f3a950c0594f16d0d01000400d7702556199051b34cf88e4e24f56bc79b172e803dd4c54581575b65578efed2", "22E4160C852A5B93F115E2897F154AAD94026CD655E1B561D33EBCC01C5C0F56"},
        {"38020000000016c3000082c30040e744000000000000000000000000010005000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310005bb781c5ed6dd4ad28eb6bd1c81668dc0db9bdeda3afc9f3a950c0594f16d0d0200050075b4c799ed97c297751aff0848a944fb4873d391b5711ed853a7b9bef96a8d93", "6E55C153C5E5AA72B5A8958473CEA28491914DD45A15E3970DA00A86C82F10EE"},
    }},
    {808476525u, "0100040003000000000000000000000000000000000000000000000006010000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f303001040003000e841f52805e0dae1b75634cc18df5878610021e6f8772f0049ff19dca775619",
     "ACCD87C1F41A4D4727B12CE6D8D42A0DC391CE2DC1861EC9DBEFC04A73A0C4BD", "F30E605363584F74545B196825B6E1789862A5417E7B4A68B9ACED44327762FD", {
        {"360200005556003899ef0f3900c0cbc400000000db0f49c000000000010106000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100accd87c1f41a4d4727b12ce6d8d42a0dc391ce2dc1861ec9dbefc04a73a0c4bd000006008e06aa8f52272f8aa9d39ccfccc11ccd17d8ea006de7d3fe941a13e786f77dcf", "763D6ECCA7CF80639D8473E154EE480DFD9006BF25C32701AB21A5946C11A83F"},
        {"37020000000016c3f58414390040bfc400000000db0f49c000000000010107000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100accd87c1f41a4d4727b12ce6d8d42a0dc391ce2dc1861ec9dbefc04a73a0c4bd01000700e984289970afb45da60dcd8b95d76208d7bf9ac1078458543ad1f388400ddce5", "0469C74AF85EE50033BB1FC0EC52A2A2B5C8C539EAD72CC16471611FB8ABBBF6"},
        {"3802000000001643f58414390040bfc400000000db0f49c000000000010108000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100accd87c1f41a4d4727b12ce6d8d42a0dc391ce2dc1861ec9dbefc04a73a0c4bd02000800ec9a0847b80b51f08db2155fdb20a4c88c1ef7f5c7aae2d27aca0340c7d70fe8", "1306DC72AD8DC5FA997BCDD98795FBB795316227421446FE4B3B3D5F5195A350"},
    }},
    {808542061u, "01000d0000000100000000000000000000000000000000000000000000000100000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f3130010d000000e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
     "8583DCD18FA3FE6800E25BB02FA61A9EB76AFC3873EDD950DE2BC11AA7D4CC9F", "3C707FF9EE6EA102BF0D06320EE9F6E2731EC1E585840F1563BC90876FD1A0A6", {
    }},
    {808542061u, "01000e0000000100000000000000010000000000000000000000000000000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f3130010e000000e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
     "D5C62C4B0B919B81F01A6551172897FE172640921434E18893B926B97C913162", "64F3C68ADB22AA4B393233AA3CFB5B39FDDD63CE0CEFC3AF68BEF7C30019704D", {
    }},
    {825319277u, "01000f000000020000000000000000000000000000000000000000000d000200000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f3131010f000000e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
     "2741A831AE85CC87743633B086DA44D90642BD86613AC4F40CE1CCE710AA40C2", "088608A03E3B4C8C2D436A9DC30D28F3C3374F656677C66E552F9854740E46FC", {
    }},
    {808935277u, "0100110003000000000000000000000000000000000000000000000000000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed0500060000000100010000006d5f373001110003002e0bf3bc42a5ffa5a1ee6d02a606bd86430f1625e0521fda7f0cf392e30c470b",
     "B2288FF579E348FABB40C56B32232041F9AC5F2F62CBC860151CF7227F95F828", "A429B48E0F9A1ABCE7B6AAD898080706ED9439A8135C2F9E67BAC7A37E60ABCA", {
        {"410100000080984305fd7fbf00c0c6c40000000091fc4740000000000000ab000200000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100b2288ff579e348fabb40c56b32232041f9ac5f2f62cbc860151cf7227f95f8280000ab00eac96ef6904205dd0a73480c61d957936ac815f2c265fee863fc30d8e1886f18", "615F9EECFD8EF25335E3A822C089DE515FF4917C730204AFA8601A9531C022E1"},
        {"41010000007037c5828be6380080d4c400000000db0fc93f0000000000000a000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100b2288ff579e348fabb40c56b32232041f9ac5f2f62cbc860151cf7227f95f82801000a00d7077b3b3752ce71a51fa1516e26bbce8f2f26a5bc8d53a300dd781416facc44", "670AC681E23D92126E9E3EA94B25DCA3142B1211D8ADEB40AE064DEBA51F0082"},
        {"4101000000203745bcec123800007a4400000000db0fc9bf00000000000009000100000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f763100b2288ff579e348fabb40c56b32232041f9ac5f2f62cbc860151cf7227f95f828020009003b92bd4fe2cd132db397a7478ba6d15f040bc875c6dfc735a95dd3c14c781851", "D09CF6DC942CE5CFBC7292C867196F59C0C85AC158F8AC3501759D8DE4C3BFC5"},
    }},
    {808476514u, "02001e0005000700000000000000000000000000000000000000000000000800000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed050006000000010001000000625f3030021e000500447e6d0f4c6e5ad652f96955d9d3db86373b7675e112fac39303429ddfd660df",
     "7D0FEC3FA57764F3F46F0B94309BF463EBE6FD1D35A42F126482ADB07FF361BB", "52092039318D0CD4C5DC24497E7DA4F6557B74A0EA0694BAC97B6DF31FA1E3A3", {
        {"2e010000c9d9fcc107000cc38726934400000000000000000000000002000b000000000000000000000008000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f7631007d0fec3fa57764f3f46f0b94309bf463ebe6fd1d35a42f126482adb07ff361bb00000b004c7be4e26233576c2b4168c6b6309a72cf4dc92cf8a58a2eb180e1a89d9fa82f", "E6AC581B9D1687B453BD39ABFCEF608D173A6AF411B30DF1BE47C0B9CFBC5720"},
        {"2e0100006132b84307000cc38726934400000000000000000000000002000c000000000000000000000008000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f7631007d0fec3fa57764f3f46f0b94309bf463ebe6fd1d35a42f126482adb07ff361bb01000c0050ff6acaa438ac10b3abb2717c7dfdeff76d5ec62c7f3542cd7f6807aef68485", "890B695D907E0186CA61174CA09D8A43348E6ECC16220F885660F7733F24D2C8"},
        {"2e0100009fcdd7c307000cc38726934400000000000000000000000002000d000000000000000000000008000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f7631007d0fec3fa57764f3f46f0b94309bf463ebe6fd1d35a42f126482adb07ff361bb02000d000cfe850ee2d2e08beb561b3b75c359820e0d8ef8451ff9b0536a2c91e1c1e9f2", "85CAD2C606E964F903AE2624C123D3D459BF078295E9AE2F3F958C32D7622AB5"},
        {"2e01000032993344000034c38726ac4400000000000000000000000002000e000000000000000000000008000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f7631007d0fec3fa57764f3f46f0b94309bf463ebe6fd1d35a42f126482adb07ff361bb03000e00463610934cd2273714f3745c2bbb2e993914c669b086cafcef765e8e267f21c7", "ECB9CDA40BC45EF78732E0208A8FF27159FE22E0DB9B11879889CE10CD1729D3"},
        {"2e010000ce6643c4070020c38726ac44000000000000000000000000020012000000000000000000000008000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f7631007d0fec3fa57764f3f46f0b94309bf463ebe6fd1d35a42f126482adb07ff361bb04001200934d68aaabce0e859ee0df263e8e1371bfcf37521146773a1dca4aca3e42e07b", "8AF28E72031CAF2114F365758703BCB2174D158C82AB4C7072E9943A619726D9"},
    }},
    {808476514u, "02001f0005000100000000000000000000000000000000000000000000000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed050006000000010001000000625f3030021f000500963f8dfddd0e5cf7acb8d002cbecb75ae9615cad0c715e5c4c201e30bea38443",
     "17D5A47AFBC7F65D0F8B6F226852BCAAAD0A839110C22891E0F576C564C19524", "57D3198E6D6909336EDDC81022624D27A12054758843AA0BA176C637FF4C6DA4", {
        {"2e0100004e5920c2179e99bf2b87aec3000000000000000000000000020013000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310017d5a47afbc7f65d0f8b6f226852bcaaad0a839110c22891e0f576c564c1952400001300166926f02923f7d6b4fce35d7f74188763ddccc0765c3049b22dbb911b647c5f", "53D03DAFE7E9B72E8CB54182C014EAE70D6D357F4076476983195C20AF262761"},
        {"2e010000b2a66f423d9999bf2b87e0c3000000000000000000000000020014000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310017d5a47afbc7f65d0f8b6f226852bcaaad0a839110c22891e0f576c564c195240100140006cf1bed8a8897258edaefe56848ed3858b548bb679a14f3152d904302df6e14", "CEF3BC32720402D33C49C80B829959A311BF0A362FD40D7732C25C2DF9A39747"},
        {"04000000d7f4cc43000000802b87c7c3000000000000000000000000020015000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310017d5a47afbc7f65d0f8b6f226852bcaaad0a839110c22891e0f576c564c19524020015002b099be2a5f7592ba63e2d35d646b42ed70a6eab4abd459fd371c9d7b883f86a", "ACF1682A5AEE6427F975DCCEA8DDBAE2EAC55E2B4D40AB20B58B9EC68B3E4077"},
        {"04000000290bc3c3000000802b87c7c3000000000000000000000000020016000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310017d5a47afbc7f65d0f8b6f226852bcaaad0a839110c22891e0f576c564c1952403001600abd0124185b467a58ca6f8332d25cc89a0d8d3d68896ec31865acc5827abc8ae", "74FE6948E4EF01D9085301E2DADB33B6706DC4562A9D565D259A919416009230"},
        {"0400000047eac4420000c8c268e1f2c3000000000000000000000000020017000000000000000000000019000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310017d5a47afbc7f65d0f8b6f226852bcaaad0a839110c22891e0f576c564c1952404001700d822933fb12fd7aa897e08a79b9d4f4dee4e46fadbad3cd9449d6a5d504a4f59", "5ACF6D86DC5A5AD415EA18625C43AAE42BF2F22D4879729081C2290BB70F9C8B"},
    }},
    {808476514u, "0200200003000100000000000000000000000000000000000000000000000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed050006000000010001000000625f3030022000030060da70f5f2b2b21af5d011be320834587b4cc9878e7261a8146291f6290230f0",
     "34B30F6966488636B9E2AB1607389E08DB282E65761C570CE7B9B9D0332828B5", "007457E16AAA24BC8C463B498F6ADED62A354F9F8D37EB8DFC7215104B22594A", {
        {"2e0100001fe12bc50cfe53b7cd08afc4000000000000000000000000020031000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310034b30f6966488636b9e2ab1607389e08db282e65761c570ce7b9b9d0332828b5000031005328b10c71b825a3ad8d1172f5ff899d8b569cd8156c3116cabed268dedc148b", "7AC74DF58FA5E3A5B344F3B7E860C4A298BA8AAD227CAC12C0939075EFE660E0"},
        {"2e0100001f8122c58b53e6b7cd48cec4000000000000000000000000020032000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310034b30f6966488636b9e2ab1607389e08db282e65761c570ce7b9b9d0332828b5010032007e1c677092eed81417eac8ebba8b3c47f7eb4cb5b8ea5eb57cce8460950f84de", "016DCC733A1DF0AACDEDFA464EE5E705D43E8015DB8FF95271B5D6996855EBB5"},
        {"2e0100001fc128c50cfe53b7cd88edc4000000000000000000000000020033000000000000000000000000000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310034b30f6966488636b9e2ab1607389e08db282e65761c570ce7b9b9d0332828b502003300e8b67ff1b189fe8de78e80d5bfa85b75dca5b7422d6bd2db95f72de3d37b0770", "6674220ADA662F55A487D0EA0331BFC9629899349B34AF555F372E3E052C734E"},
    }},
    {808476514u, "0200210004000100000000000000000000000000000000000000000000000000000000000000000000000000",
     "4b48324f7264696e6172794172726179436f6d706172652f7631009002b2de6a1f91a790bd0673de125d1cf833f7942bfec827cdcf6ba64d5849ed050006000000010001000000625f30300221000400e5afae736388507c08615682b5643b1eb75ca306f97cd9e11e3feab5f1ebf884",
     "09E9BBAC5F2292FD88E5920E454BAB88ECBE04B80BDA54CDBA0A26E1EEC9935C", "CBCD1D3AEC749450524D94BC36B4B1A39262F071CC16D36E91E2924F6096D374", {
        {"040000000806204500000080a88a9d44000000000000000000000000020034000000000000000000000019000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310009e9bbac5f2292fd88e5920e454bab88ecbe04b80bda54cdba0a26e1eec9935c00003400ebef4428e363d90f9c98068f1237990dac77ff97fe0043714e12afe46a303ae3", "66146182F99455108664C6F70C287B99AB2F46115187751A4C5126E82ED0D43E"},
        {"0400000008862c45000048c24d157044000000000000000000000000020035000000000000000000000019000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310009e9bbac5f2292fd88e5920e454bab88ecbe04b80bda54cdba0a26e1eec9935c010035001e25b1d026d98685aae54e57be9dd79bebef7276bc74ab63982e522b5199a4dd", "CF3C75349ED9A492898E19E95D29D1C917847D44C691B688544F02B773AAE278"},
        {"04000000084626450000c8c24d152544000000000000000000000000020036000000000000000000000019000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310009e9bbac5f2292fd88e5920e454bab88ecbe04b80bda54cdba0a26e1eec9935c02003600bf286a51a8d48861b52ad6571613ff291bd7371c391b4a4ec3f6fff40ea8809c", "F6E5808CC5C99F4A63B78C84544C2FA9966EA83BDEB8B095EFBE5676FE3550D0"},
        {"0400000008c61945000048c34d157044000000000000000000000000020037000000000000000000000019000000000000000000000000000000000000000000",
         "4b48324f7264696e6172795265636f7264436f6d706172652f76310009e9bbac5f2292fd88e5920e454bab88ecbe04b80bda54cdba0a26e1eec9935c030037000b9d7cc077549ca828c9ccb21c614bd2b1ac22b09203938d9e430e03357f43cb", "A9000AADCC4B38D3DA28063FE5F3E74ABB48543150169CCCAEC7C93E1DC13516"},
    }},
};
const auto layout = fixed<32>("9002B2DE6A1F91A790BD0673DE125D1CF833F7942BFEC827CDCF6BA64D5849ED");

std::vector<NativeRecordContentDefinition> definitions() {
    std::vector<NativeRecordContentDefinition> result;
    for (const auto& g : goldens) {
        NativeRecordContentDefinition d;
        d.layoutSha256=layout; d.location={5,6,0,1,1,0};d.groupKey=g.group;d.header=fixed<44>(g.header);
        for(const auto& r:g.records)d.records.push_back(fixed<64>(r.raw));
        result.push_back(std::move(d));
    }
    return result;
}
void count(NativeRecordContentDefinition& d, std::uint16_t n) {
    d.header[4]=static_cast<std::uint8_t>(n);d.header[5]=static_cast<std::uint8_t>(n>>8);
}
void id(std::array<std::uint8_t,64>& record,std::uint16_t n) {
    record[30]=static_cast<std::uint8_t>(n);record[31]=static_cast<std::uint8_t>(n>>8);
}
} // namespace
int main() {
    using S=NativeRecordContentStatus;
    auto defs=definitions();
    static_assert(sizeof(decltype(NativeRecordLocation::world))==2);
    static_assert(std::tuple_size_v<decltype(NativeRecordContentDefinition::header)> == 44);
    std::size_t records=0;
    for(std::size_t i=0;i<defs.size();++i) {
        const auto before=defs[i];const auto result=BuildNativeRecordContent(defs[i]);
        check(result.status==S::Complete,"actual definition content is complete, including type1 and empty");
        check(result.encoding==hex(goldens[i].encoding)&&result.comparisonSha256==fixed<32>(goldens[i].digest),"actual exact definition encoding and digest match independent golden");
        check(desyncSha256(result.headerProjection)==fixed<32>(goldens[i].projectionDigest),"actual header projection matches independent golden");
        check(defs[i].header==before.header&&defs[i].records==before.records,"builder preserves complete raw evidence");
        check(result.records.size()==goldens[i].records.size(),"actual full ordered record count retained");
        for(std::size_t j=0;j<result.records.size();++j) {
            const auto& actual=result.records[j];const auto& expected=goldens[i].records[j];
            check(actual.encoding==hex(expected.encoding)&&actual.comparisonSha256==fixed<32>(expected.digest)&&actual.nativeIndex==j,
                "actual exact record encoding/digest/index match independent golden");
            ++records;
        }
    }
    check(records==26&&defs.size()==10,"all actual 10 definitions / 26 records exercised");
    auto modified=defs[6];modified.header[14]^=1;
    check(CompareNativeRecordContent(defs[6],modified).equal&&BuildNativeRecordContent(defs[6]).encoding==BuildNativeRecordContent(modified).encoding,
        "header +E exclusion affects neither comparison nor definition encoding");
    check(modified.header[14]!=defs[6].header[14],"excluded marker remains visible in raw evidence");
    bool otherHeaderBytes=true;
    for(std::size_t i=0;i<44;++i)if(i!=14) {
        auto changed=defs[6];changed.header[i]^=1;
        otherHeaderBytes=otherHeaderBytes&&!CompareNativeRecordContent(defs[6],changed).equal;
    }
    check(otherHeaderBytes,"every other header byte participates or invalidates shape");
    modified=defs[6];modified.header[15]^=1;
    check(BuildNativeRecordContent(modified).comparisonSha256==BuildNativeRecordContent(defs[6]).comparisonSha256&&
          !CompareNativeRecordContent(modified,defs[6]).equal,"equal descriptor hashes cannot bypass exact header sidecar");
    bool fullRecordBytes=true;
    for(std::size_t i=0;i<64;++i) { auto changed=defs[6];changed.records[0][i]^=1;fullRecordBytes&=!CompareNativeRecordContent(defs[6],changed).equal; }
    check(fullRecordBytes,"every full record byte participates in content equality");
    modified=defs[6];std::swap(modified.records[0],modified.records[1]);
    check(!CompareNativeRecordContent(modified,defs[6]).equal&&BuildNativeRecordContent(modified).comparisonSha256!=BuildNativeRecordContent(defs[6]).comparisonSha256,"native record order is significant");
    auto forged=BuildNativeRecordContent(modified);forged.comparisonSha256=BuildNativeRecordContent(defs[6]).comparisonSha256;
    check(!CompareNativeRecordContent(modified,defs[6]).equal,"modified derived digest cannot affect raw equality");
    auto a=BuildNativeRecordContent(defs[2]), b=BuildNativeRecordContent(defs[3]);
    check(a.arraySha256==b.arraySha256&&a.comparisonSha256!=b.comparisonSha256&&!CompareNativeRecordContent(defs[2],defs[3]).equal,"empty arrays remain distinguished by complete descriptor");
    modified=defs[6];modified.records.pop_back();check(BuildNativeRecordContent(modified).status==S::Partial,"missing declared record is partial");
    modified=defs[6];modified.records.push_back(modified.records[0]);check(BuildNativeRecordContent(modified).status==S::Unavailable,"excess record/header disagreement is unavailable");
    modified=defs[6];modified.layoutSha256={};check(BuildNativeRecordContent(modified).status==S::Unavailable,"unknown layout identity is unavailable");
    modified=defs[6];modified.records.resize(257);count(modified,257);check(BuildNativeRecordContent(modified).status==S::Unsupported,"per-definition diagnostic cap is explicit");
    modified.records.resize(65536);count(modified,0);check(BuildNativeRecordContent(modified).status==S::Unsupported,"overflowing record size cannot truncate to u16");
    modified=defs[6];modified.records.resize(256);count(modified,256);
    for(std::size_t i=0;i<modified.records.size();++i)id(modified.records[i],static_cast<std::uint16_t>(i));
    check(BuildNativeRecordContent(modified).status==S::Complete,"exact per-definition cap remains supported content");
    std::vector<NativeRecordContentDefinition> boundary(4,modified);
    std::vector<NativeRecordContentCandidate> boundaryCandidates;
    for(std::size_t i=0;i<boundary.size();++i) {
        boundary[i].groupKey=static_cast<std::uint32_t>(i);
        for(std::size_t j=0;j<256;++j)id(boundary[i].records[j],static_cast<std::uint16_t>(i*256+j));
        boundaryCandidates.push_back({&boundary[i],S::Complete,true});
    }
    check(ResolveNativeRecordContent(boundary[0],boundaryCandidates,S::Complete).status==S::Complete,"exact aggregate 1024-record cap resolves without overflow");
    std::vector<NativeRecordContentDefinition> emptyBoundary(64,defs[2]);boundaryCandidates.clear();
    for(std::size_t i=0;i<emptyBoundary.size();++i){emptyBoundary[i].groupKey=static_cast<std::uint32_t>(i);boundaryCandidates.push_back({&emptyBoundary[i],S::Complete,true});}
    check(ResolveNativeRecordContent(emptyBoundary[63],boundaryCandidates,S::Complete).definitionIndex==63,"exact 64-definition cap resolves last unique empty descriptor");
    const auto wide=MakeNativeRecordLocation({65535,65535,65535,65535,65535,65535});
    check(wide&&wide->eventProgram==65535,"comparison representation accepts full u16 location widths");
    bool widths=true;for(std::size_t i=0;i<6;++i){std::array<std::uint32_t,6> v{};v[i]=65536;widths&=!MakeNativeRecordLocation(v).has_value();}
    check(widths,"each wider location field is rejected before narrowing");
    modified=defs[6];modified.location=*wide;modified.groupKey=0xffffffffu;modified.header[0]=0xff;modified.header[2]=modified.header[3]=0xff;
    check(BuildNativeRecordContent(modified).status==S::Complete,"content retains full group/type/header/location widths without behavioral eligibility");
    modified=defs[6];id(modified.records[0],0);id(modified.records[1],0x8000);id(modified.records[2],0xffff);
    auto ids=BuildNativeRecordContent(modified);
    check(ids.status==S::Complete&&ids.records[0].rawId==0&&ids.records[1].rawId==0x8000&&ids.records[2].rawId==0xffff,"zero/high-bit/full u16 IDs are representable content");
    std::vector<NativeRecordContentCandidate> catalog;
    for(const auto& def:defs)catalog.push_back({&def,S::Complete,true});
    for(std::size_t i=0;i<defs.size();++i) {
        const auto resolved=ResolveNativeRecordContent(defs[i],catalog,S::Complete);
        check(resolved.status==S::Complete&&resolved.definitionIndex==i&&!resolved.recordIndex,"all actual definitions resolve uniquely, including repeated groups");
        for(std::size_t j=0;j<defs[i].records.size();++j){const auto r=ResolveNativeRecordContentRecord(defs[i],j,catalog,S::Complete);
            check(r.status==S::Complete&&r.definitionIndex==i&&r.recordIndex==j,"actual record resolves by exact native index and complete array");}
    }
    auto resolve=[&](const auto& cat,S status=S::Complete){return ResolveNativeRecordContent(defs[6],cat,status);};
    check(resolve(catalog,S::Partial).status==S::Partial,"partial whole catalog cannot become unique");
    check(resolve(catalog,S::Unavailable).status==S::Unavailable,"unavailable whole catalog retained");
    check(resolve(catalog,S::NoMatch).status==S::Unavailable,"no-match cannot be supplied as catalog coverage");
    check(resolve(catalog,static_cast<S>(999)).status==S::Unavailable,"unknown catalog status fails closed");
    auto invalidCandidate=catalog;invalidCandidate[0].status=S::NoMatch;
    check(resolve(invalidCandidate).status==S::Unavailable,"candidate no-match does not fabricate whole-scope absence");
    auto bad=catalog;bad[0].status=S::Unsupported;check(resolve(bad).status==S::Unsupported,"unsupported unrelated candidate blocks complete-scope resolution");
    bad=catalog;bad[0].associationUnique=false;check(resolve(bad).status==S::Ambiguous,"reader-reported controller/array alias blocks resolution");
    bad=catalog;bad[0].definition=nullptr;check(resolve(bad).status==S::Unavailable,"missing evidence does not imply absence");
    bad=catalog;bad.push_back(catalog[6]);check(resolve(bad).status==S::Ambiguous,"repeated evidence pointer never selects first candidate");
    auto duplicate=defs[6];bad=catalog;bad.push_back({&duplicate,S::Complete,true});check(resolve(bad).status==S::Ambiguous,"independent equal definition copy remains ambiguous");
    duplicate.header[15]^=1;check(resolve(bad).status==S::Ambiguous,"duplicate descriptor with conflicting header projection remains ambiguous");
    duplicate=defs[0];id(duplicate.records[0],11);bad=catalog;bad[0].definition=&duplicate;check(resolve(bad).status==S::Ambiguous,"duplicate raw ID in another definition blocks unique association");
    duplicate=defs[6];id(duplicate.records[1],11);bad=catalog;bad[6].definition=&duplicate;check(resolve(bad).status==S::Ambiguous,"duplicate raw ID inside an array blocks unique association");
    bad=catalog;bad[0].status=S::Partial;check(resolve(bad).status==S::Partial,"partial unrelated candidate cannot be omitted");
    bad.resize(65,catalog[0]);check(resolve(bad).status==S::Unsupported,"catalog entry cap checked before matching");
    duplicate=defs[6];duplicate.records.resize(256);count(duplicate,256);bad.assign(5,{&duplicate,S::Complete,true});
    check(resolve(bad).status==S::Unsupported,"aggregate record cap checked before duplicate resolution");
    modified=defs[6];modified.groupKey^=1;check(ResolveNativeRecordContent(modified,catalog,S::Complete).status==S::NoMatch,"complete genuinely absent descriptor reports no match");
    modified=defs[6];modified.header[15]^=1;check(ResolveNativeRecordContent(modified,catalog,S::Complete).status==S::NoMatch,"same digest with different header bytes cannot resolve");
    check(ResolveNativeRecordContent(defs[6],{},S::Complete).status==S::NoMatch,"explicitly complete empty catalog reports no match");
    check(ResolveNativeRecordContentRecord(defs[6],5,catalog,S::Complete).status==S::Unavailable&&
          ResolveNativeRecordContentRecord(defs[6],std::numeric_limits<std::size_t>::max(),catalog,S::Complete).status==S::Unavailable,
          "record index outside exact extent never narrows or wraps");
    check(ResolveNativeRecordContentRecord(defs[2],0,catalog,S::Complete).status==S::Unavailable,"empty definition has no resolvable record");
    std::cout << checks-errors << " PASS / " << errors << " FAIL\n";
    return errors ? 1 : 0;
}
